### ISSUE TITLE
Stopped working in Sketch 52

### ISSUE THREAD

**Issue by TBVTBV** [atlassian/jira-cloud-for-sketch#15]
Please help! in Sketch 52 it stopped working! no Jira icon in the make exportable tab ):

**Comment by kannonboy** [comment]
Good news everyone!

We released Jira Cloud for Sketch v1.1.3 today, which fixes the crashing bug. You can [download it here](https://s3-us-west-2.amazonaws.com/atlassian-sketch-plugin/jira.sketchplugin-1.1.3.zip), or follow the "Plugin Updates Available" prompt within Sketch if you still have an earlier version installed.

Note: There remains a regression under Sketch 52+ where the Jira button no longer appears on the export panel due to some changes in the Sketch UI layout. However, you can still open the Jira panel via the Plugins menu, or by pressing ⌥⌘J

Thanks for your patience folks!

**Comment by TBVTBV** [comment]
Hi!
Thanks for the answer, but not it will not connect at all.
this was the address I've used before but now it will not work: jira.team.hometalk.com
